### ISSUE TITLE
Cut/Copy/Paste and drag'n'drop loops

### ISSUE THREAD

**Issue by unfa** [openAVproductions/openAV-Luppp#265] opened 2018-12-12 19:39 UTC
I've just tried out Luppp, and I expected I will be able to drag my loops around into different slots to relocate them once I load them - looks like it's not possible.

I also thought there could be a Cut/Copy/Paste functionality there - it's missing too.

Maybe a simple mouse drag'n'drop could relocate a loop, and Ctrl+drag could duplicate the loop to a selected slot? That'd be very convenient for reorganizing the project. Right now it doesn't feel like Luppp is encouraging experimentation, but rather preparing something I've planned ahead and already know how it should be laid out.

Or maybe these functions are there, but I just didn't find them? Then I guess they probably should be better exposed :)

**Comment by trebmuh** [comment] 2018-12-12 20:23
Don't know if that's applying to your case (I'm not a heavy Luppp user), but I thought that mentioning the [Luppp manual](http://openavproductions.com/doc/luppp.html) here might help. Here it is.

**Comment by harryhaaren** [comment] 2018-12-13 05:43
Hey @unfa - indeed these functions don't exist properly today - it seems a very simple issue, implementation is not hugely complex either (due to Luppp's very basic audio-buffer handling). This is a good UX feature request, unfortunately I'm way busy at the moment (and next month or 2 too) so I won't be implementing this soon - sorry. Lets leave this issue in open and "feature request" state, then see if/when a time or other developers join in on this.

**Comment by georgkrause** [comment] 2019-03-28 12:04
Duplicate of #155

**Closed by georgkrause** 2019-03-28 12:04 UTC
Labels: Feature Request
